language: groovy
cache:
  directories:
    - node_modules
    - ModelCatalogueCorePlugin/target/work/plugins
    - ModelCatalogueCorePluginTestApp/target/work/plugins
    - $HOME/.m2
    - $HOME/.grails/ivy-cache
    - $HOME/.grails/wrapper

env:
  - TEST_SUITE=core_unit
  - TEST_SUITE=core_integration
  - TEST_SUITE=core_integration_slow
  - TEST_SUITE=app_integration
  - TEST_SUITE=app_functional
  - TEST_SUITE=forms_integration
jdk:
  - oraclejdk7
before_install:
  - "export DISPLAY=:99.0"
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1920x1080x24"
script:
  - "./run-all-tests.sh"
after_script:
  - "./update-gh-pages.sh"
